### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by liyue201** [eostoken/ET-exchange#6]
exchange_state.hpp 26行
double weight = .5;

exchange_state.cpp 11 行
real_type F(c.weight/1000.0);

 这里不应该除以1000了，eos源码有类似的代码，它除以1000是因为它里面定义的 weight = 500;

**Comment by stev1988** [comment]
这个值是多少其实关系不大的，因为这里面用的是双bancor算法，weight可以近似被约掉的，可以参考https://blog.eospark.com/basicconcept.html

**Comment by stev1988** [comment]
后续再有更新的话，我们会把这个去掉的，感谢您的提醒。
